name: RUN
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'
    - run: php ./portable.php > index.html
    - run: php ./portable-feed.php > feed.xml
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build website (automatic)
