name: RUN
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'
    - run: php ./portable.php > index.html
    - run: php ./portable-feed.php > feed.xml
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build website (automatic)
    - uses: mvasigh/dispatch-action@main
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repo: quarto-blog
        owner: ${{secrets.PAT_USERNAME}}
        event_type: sample_push
